pipeline {
  agent any

  environment {
    CI = "false" // Evita que React trate los warnings como errores
    VERCEL_TOKEN = credentials('vercel-token')
  }

  tools {
    nodejs 'Node 20' // Instalación limpia de NodeJS
  }

  stages {
    stage('Clean workspace') {
      steps { deleteDir() }
    }

    stage('Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/DMaTeoG/game-proyect-1-player_copia.git'
      }
    }

    stage('Show workspace files') {
      steps {
        bat 'dir'
      }
    }

    stage('Install dependencies') {
  steps {
    dir('game-project') {
      bat 'npm install --legacy-peer-deps'}
      }
    }
      
    stage('Run ToyCarLoader Unit Test') {
      steps {
        bat 'npx vitest run src/loaders/tests/ToyCarLoader.test.js'
      }
    }

    stage('Build app') {
      steps { bat 'npm run build' }
    }

    stage('Deploy to Vercel') {
      steps {
        bat "npx vercel --prod --token=%VERCEL_TOKEN% --confirm"
      }
    }
  }

  post {
    success {
      echo '✅ Deploy exitoso en Vercel.'
    }
    failure {
      echo '❌ El pipeline falló.'
    }
  }
}
